import turtle
import math

window = turtle.Screen()
tortuga = turtle.Turtle()
tortuga.penup()
tortuga.setposition(-300,250)
tortuga.pendown()
print(tortuga.position())

#T
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(37.5)
tortuga.left(90)
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(100)
tortuga.left(90)
tortuga.forward(37.5)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.penup()

#E

tortuga.forward(125)
tortuga.pendown()
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(75)
tortuga.left(90)
tortuga.forward(25)
tortuga.left(90)
tortuga.forward(60)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(60)
tortuga.left(90)
tortuga.forward(25)
tortuga.left(90)
tortuga.forward(75)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.penup()

#Espacio



#P

tortuga.forward(225)
tortuga.pendown()
tortuga.forward(50)
tortuga.circle(-40,180)
tortuga.forward(25)
tortuga.penup()
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.pendown()
tortuga.forward(25)
tortuga.circle(15,180)
tortuga.forward(25)
tortuga.left(90)
tortuga.forward(30)
tortuga.penup()
tortuga.forward(25)
tortuga.pendown()
tortuga.forward(45)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.penup()

#I
tortuga.forward(115)
tortuga.pendown()
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.penup()

#E

tortuga.forward(50)
tortuga.pendown()
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(75)
tortuga.left(90)
tortuga.forward(25)
tortuga.left(90)
tortuga.forward(60)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(60)
tortuga.left(90)
tortuga.forward(25)
tortuga.left(90)
tortuga.forward(75)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.penup()

#N

a = (100/math.sin(math.radians(60)))
print(a)
b = (25*math.sin(math.radians(60)))
c = (25*math.sin(math.radians(30)))
d = (25*math.tan(math.radians(30)))
print(25+d)
tortuga.forward(125)
tortuga.pendown()
tortuga.forward(25+d)
tortuga.right(60)
tortuga.forward(a)
tortuga.left(150)
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.forward(25+d)
tortuga.right(60)
tortuga.forward(a)
tortuga.left(150)
tortuga.forward(100)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.forward(125)
tortuga.right(90)
tortuga.penup()

#S
aa = (35*math.sin(math.radians(50)))
bb = (10*math.sin(math.radians(50)))
sa = (35*math.cos(math.radians(50)))
sb = (10*math.cos(math.radians(50)))
distancia = (125-aa-bb-70)
sc = ((distancia)/math.sin(math.radians(40)))
sd = (((sa+sb))/math.sin(math.radians(40)))
print("distancia")
print(distancia)
print(sd)
print(sc)
print(aa)
print(bb)
ads = 115+d+(a*math.cos(math.radians(60)))
tortuga.forward(ads)
tortuga.pendown()
tortuga.circle(-35,90)
tortuga.right(90)
tortuga.forward(25)
tortuga.left(90)
tortuga.circle(-10,-230)
tortuga.left(180)
tortuga.forward(sc)
tortuga.circle(-35,50)
tortuga.circle(-35,180)
tortuga.right(90)
tortuga.forward(25)
tortuga.right(90)
tortuga.circle(10,230)
#tortuga.left(20)
tortuga.forward(sc)
tortuga.circle(-35,50)
tortuga.circle(-35,90)
tortuga.penup()

#O
tortuga.forward(95)
tortuga.pendown()
tortuga.circle(-35,90)
tortuga.forward(55)
tortuga.circle(-35,180)
tortuga.forward(55)
tortuga.circle(-35,90)
tortuga.penup()
tortuga.right(90)
tortuga.forward(25)
tortuga.left(90)
tortuga.pendown()
tortuga.circle(-10,90)
tortuga.forward(55)
tortuga.circle(-10,180)
tortuga.forward(55)
tortuga.circle(-10,90)

window.mainloop()
turtle.done()